# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --editable ".[dev]"
    - name: Format code with black
      run: |
        black -l 100 geneeval
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 geneeval --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 geneeval --count --exit-zero --max-complexity=10 --max-line-length=115 --statistics
    - name: Test with pytest
      run: |
        pytest tests -rf --cov ./geneeval --cov-report=xml --cov-config=./.coveragerc 
    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.7' && matrix.os == 'ubuntu-latest' && github.event_name == 'push'
      uses: codecov/codecov-action@v1.0.10
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
